name: Scheduled Tweet Posting

on:
  schedule:
    # Run every 3 hours
    - cron: '0 */3 * * *'
  # Allow manual trigger
  workflow_dispatch:

jobs:
  build:
    name: Auto Tweet Using AI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm i
      - name: Run Twitter bot
        run: npm start
        
